pipeline {
	agent {
	label 'nodejs'
}
stages {
stage ('Install Dependencies') {
	steps {
	dir ('exchange-cli') {
	sh "npm install"
}
}
}
	stage ('Build') {
	steps {
	dir ('exchange-cli') {
	sh "npm run build"
}
}
}
	stage ('Unit Tests By Satish Mane') {
	steps {
	dir ('exchange-cli') {
	sh "npm run test:unit"
}
}
}
	stage ('Functional Test Satish') {
	steps {
	dir ('exchange-cli') {
	sh "npm run test:functional"
}
}
}
}
}
